
[Interface]
PrivateKey = KPiRpywimB6A6WuUVSVZ1aaC18pdRW/ObxJnwf9TMEg=
Address = 10.8.0.2/24
DNS = 192.168.1.1

[Peer]
PublicKey = Kg6SwXp2cawNFD8JLQpGIJuyMvgCaPEaiHau0bg/c2M=
PresharedKey = M5oydNoGGS0TEA6Te/PGOCnv3I0r3vv7HstuOeVGON8=
AllowedIPs = 192.168.1.0/24
PersistentKeepalive = 0
Endpoint = 38.137.4.71:51820
